server:
  port: 8081

spring:

  kafka:

    consumer:

      bootstrap-servers: ["172.18.0.3:9092"]
      offset-type: earliest
      topic-name: kafka-test
      group-id: "test"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer